name: flutter_demo_1
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.7.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/png/
    - assets/svg/
#    - assets/audios/
    - assets/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/OpenSans-LightItalic.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf

